#!/usr/bin/env bash
# This script prints Holberton School ten times with Hi after the 9th.

i=1
while [ $i -le 10 ]; do
      echo "Holberton School"
      if [ $i -eq 9 ]; then
      	 echo "Hi"
      fi
      i=$(( i + 1 ))
done
