#!/usr/bin/env bash
# This script displays the content of the current directory in list format with only the part of the name after the first dash.

for f in $(find . ! -name ".*" | cut -d "-" -f 2); do
    echo "$f"
done
