#!/usr/bin/env bash
# This script displays the content of the current directory in list format with only the part of the name after the first dash.

fils=$(ls)
for f in $fils; do
    echo "$f" | cut -d "-" -f 2
done
