#!/usr/bin/env bash
#Set Up NGINX server to return a page that contains string

sudo apt-get -y install nginx
sudo mkdir -p /data/www
echo "Holberton School for the win!" > index.html
sudo cp index.html /data/www/
sudo cat > default <<EOF
events {
    worker_connections 768;
}
http {
    server {
        listen 80 default_server;
        root /data/www;
        location / {
            index index.html index.html;
        }
    }
}
EOF
sudo cp default /etc/nginx/sites-available/default
sudo service nginx restart
