#!/usr/bin/env bash
#Sets Up NGINX server to return a page that contains string

sudo apt-get -y install nginx
sudo mkdir -p /etc/nginx/html
cd /etc/nginx/html
echo "Holberton School for the win!" > index.html
cd /etc/nginx/sites-available
echo "server {
    listen 80 default_server;
    root /data/www;
    location / {
        index index.html index.html;
    }
}" > default
sudo service nginx restart
