#!/usr/bin/env bash
#Set Up NGINX server to return a page that contains string

apt-get -y install nginx
mkdir -p /data/www
echo "Holberton School for the win!" > index.html
cp index.html /data/www/
cat > default <<EOF
server {
    listen 80 default_server;
    root /data/www;
    location / {
        index index.html index.html;
    }
    location /redirect_me {
        return 301 https://google.com;
    }
}
EOF
cp default /etc/nginx/sites-available/default
cat > nginx.conf <<EOF
events {
}
http {
    server {
        listen 80 default_server;
        root /data/www;
        location / {
            index index.html index.html;
        }
        location /redirect_me {
            return 301 https://google.com;
        }
    }
}
EOF
cp nginx.conf /etc/nginx/nginx.conf
sudo service nginx restart
