#!/usr/bin/env bash
# Script modifies /etc/hosts file to change localhost and the IP of a site

FILE="/etc/hosts"
TFILE="/etc/hoststemp"
cp "$FILE" "$TFILE"
sed -i -e 's/127.0.0.1/127.0.0.2/g' "$TFILE"
echo "8.8.8.8 facebook.com" >> "$TFILE"
cp "$TFILE" "$FILE"
